import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  // Use environment variable for the base URL, falling back to the production URL
  const baseUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://packwise-indol.vercel.app'
  const cleanBaseUrl = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl

  // SEO Rationale: Expose public static routes to search engines for indexation.
  // We deliberately omit the `lastModified: new Date()` anti-pattern for static routes,
  // as it inaccurately tells crawlers the content changes on every build/request,
  // which can lead to crawl budget waste and decreased trust in sitemap signals.
  return [
    {
      url: `${cleanBaseUrl}/`,
      changeFrequency: 'monthly',
      priority: 1,
    },
    {
      url: `${cleanBaseUrl}/login`,
      changeFrequency: 'yearly',
      priority: 0.8,
    },
    // Note: Shared trip routes (/trip/[id]) are omitted from the sitemap as they are
    // dynamically generated by users and should not be proactively crawled/indexed
    // unless explicitly shared/linked elsewhere.
  ]
}
