export const packingAdvice = [
  "Remember you can always buy things when you get there.",
  "Less is more. If you're debating whether to bring it, leave it.",
  "Roll your clothes instead of folding to save space and reduce wrinkles.",
  "Pack a reusable water bottle to save money and stay hydrated.",
  "Keep your heaviest items at the bottom of your bag.",
  "Wear your bulkiest shoes and heaviest jacket on the plane.",
  "Use packing cubes to stay organized and compress your clothing.",
  "Always pack an extra pair of underwear and socks in your carry-on.",
  "Bring a universal travel adapter to charge your devices anywhere.",
  "Download offline maps in case you lose cellular service.",
  "Pack versatile clothing that can be mixed and matched easily.",
  "A sarong or large scarf can serve as a blanket, towel, or wrap.",
  "Keep photocopies of your passport and important documents separate from the originals.",
  "Store cables and chargers in an old sunglasses case to prevent tangling.",
  "Put heavy items near the wheels of your suitcase for better balance.",
  "Pack a small first-aid kit with essentials like pain relievers and bandages.",
  "Bring a laundry bag to separate dirty clothes from clean ones.",
  "Stick to a color palette to maximize outfit combinations.",
  "Always keep essential medications in your carry-on bag.",
  "Use solid toiletries (like bar shampoo) to avoid the liquid limit.",
  "Stuff socks inside your shoes to save space and help shoes keep their shape.",
  "A lightweight, packable daypack is essential for exploring.",
  "Bring a portable power bank so your phone never dies while navigating.",
  "Pack layers instead of thick, bulky items to adapt to changing weather.",
  "Take photos of your luggage before checking it in.",
  "Bring a few ziplock bags; they are surprisingly useful for wet clothes or snacks.",
  "Pack a pen. You'll often need one for customs forms on the plane.",
  "Bring travel-sized detergent to wash essentials in the sink if needed.",
  "Don't pack 'just in case' items—pack 'I will definitely use this' items.",
  "Weigh your luggage at home to avoid surprise fees at the airport.",
  "A digital luggage scale can save you money on return flights.",
  "Check the local weather forecast one day before packing.",
  "Pack a physical book or e-reader for long layovers and flights.",
  "Keep valuables (laptop, camera, jewelry) in your carry-on, never checked.",
  "Use a pill organizer for your daily vitamins or medications.",
  "Bring earplugs and an eye mask for better sleep on planes or in noisy hotels.",
  "Pack a small travel umbrella or a lightweight rain poncho.",
  "If traveling with a partner, mix half your items in each other's bags just in case one gets lost.",
  "Store belts unrolled along the inside edge of your suitcase.",
  "Bring a quick-dry travel towel if you're staying in hostels.",
  "Use contact lens cases for small amounts of lotion or foundation.",
  "Pack a collapsible tote bag for souvenirs or grocery runs.",
  "Choose comfortable walking shoes over stylish but painful ones.",
  "Bring a small sewing kit for emergency repairs on the go.",
  "Keep an emergency $50 or €50 stashed separately from your main wallet.",
  "Pack a deck of cards—a great way to pass time and make friends.",
  "Bring wet wipes and hand sanitizer for quick clean-ups.",
  "A small stash of your favorite tea bags or instant coffee can be a lifesaver.",
  "Check your passport expiration date months before your trip.",
  "Embrace the adventure! If you forget something, figuring it out is part of the journey."
];
